### ISSUE TITLE
En el formulario Visitas solo debe verse fecha, hora y anotación. El resto invisible

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dmencu#110]
(si se pueden calular mejor, si no no, pero que no se vean para no confundir)

**Comment by GracielaCanessa** [comment]
Comienzo a ocultar esos campos en el formulario de Visitas para el encuestador

**Comment by GracielaCanessa** [comment]
Por el momento tanto en los formularios VIS y RE_VIS(de supervisión) colocamos "ocultar" en despliegue y e "INHABLITAR" en expresion_habilitar en los campos renglón, rol, persona y usuario para que no se muestren en los formularios.
