### ISSUE TITLE
revisar error asignante en tareas-tem

### ISSUE THREAD

**Issue by manueldelapenna** [codenautas/dmencu#126]

**Comment by GracielaCanessa** [comment]
Asignante se refleja ahora en tareas_tem .Realizado en https://github.com/codenautas/dmencu/commit/f3bda4d2f10183a46403504a877268443df702ca . Correr junto a script [operaciones/2022-04-18-actualizar.sql](https://github.com/codenautas/dmencu/commit/f3bda4d2f10183a46403504a877268443df702ca#diff-e2368ced3d13bb1bbcac0e96252d3a854bead16963e61ea4ad79cd7016e08ad1)
