### ISSUE TITLE
Agregar un campo resultado, efectiva, no encuestable, no rea encuestable, pendiente

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dmencu#128]
El campo resultado se calcula en cadena así:
   * realizada = 3 es 'pendiente'
   * realizada = 1 es 'efectiva'
   * norea se busca en la tabla de noreas. 
   * etc...

**Comment by GracielaCanessa** [comment]
Agrego comunas.tab necesario para los controles por comuna y zona en https://github.com/codenautas/dmencu-data/commit/12e6280e0f2cd377469c30bc8c00b937f9a44612

**Comment by GracielaCanessa** [comment]
Ajustes considerando el dominio en los controles  d3ac67b

**Comment by GracielaCanessa** [comment]
Listo realizado.
