### ISSUE TITLE
La "aclaración_superior" de las preguntas deben insertarse como TEXTO

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dmencu#35]
Casillero TEXTO = texto libre, agregar en casillero si hace falta.

Ver si se despliega o hay que agregar el despliegue. 

Hacer los insert en los metadatos con orden - 1

**Comment by GracielaCanessa** [comment]
Comienzo a armar script para recuperar las preguntas con aclaración superior del esquema encu.

**Comment by GracielaCanessa** [comment]
agrego primera versión  consulta para aclaraciones_superiores en migrar_a_casilleros.sql.
Falta agregar el despliegue de los casilleros tipoc='TEXTO'.

**Comment by GracielaCanessa** [comment]
-Falta agregar el despliegue de los casilleros tipoc='TEXTO'.
Lo agregamos en el commit  **f0f581a**

**Comment by GracielaCanessa** [comment]
Los metadatos ya están cargados (corresponden a las preguntas con valor en campo aclaracion_superior. Queda pendiente agregar la funcionalidad dentro del sistema para visualizar los valores correspondientes.
