### ISSUE TITLE
Agregar el formulario de vistias colgando de viviendas

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dmencu#51]
No poner ni fecha ni hora en forma automática. 
Pasos:

- [x] https://github.com/codenautas/dmencu-data/issues/3

**Comment by GracielaCanessa** [comment]
complementando las tareas de metadatos realizadas en[https://github.com/codenautas/dmencu-data/issues/3](url), se actualiza bypass-formulario.ts para la visualización del formulario de visitas.

**Comment by GracielaCanessa** [comment]
Realizado en issue  codenautas/dmencu-data#3 .
