### ISSUE TITLE
Emprolijar la TEM.

### ISSUE THREAD

**Issue by emilioplatzer** [codenautas/dmencu#55]
Que solo queden las geográficas, las que permiten lotear (semana) y algunas tipos REA, NOREA, cantidad de personas, las que parezcan imprescindibles.

**Comment by RaquelSalva** [comment]
Comencé haciendo una primera limpieza en [77b958df204cacdadc350543735b93d8c185dfac]

**Comment by RaquelSalva** [comment]
Cerramos como está. Vamos a avanzar con calculo de Rea
